pankona/hashira

database/boltdb_test.go
detected by gometalinter (vetshadow)
=> avoid shadowing of err variable

.golangci.yml, cmd/hashira-cui/editor.go, cmd/hashira-cui/keybinding.go, cmd/hashira-cui/view.go
Keybindings while editing have been updated as follows:
- C-f to move cursor forward (without editing)
- C-b to move cursor backword (without editing)
- C-a to move cursor on start of line
- C-e to move cursor on end of line
- C-d to delete a character on cursor
- C-h is now same as Backspace (delete and move cursor -1)
=> [#49] Update keybinding while editing

Gopkg.lock, Gopkg.toml, go.mod, go.sum
- use pankona/gocui instead of jesseduffield/gocui temporarily.
- fix an issue: backspace sometimes doesn't work if the line includes wide charactor.
=> [#69] fix backspace while editing

cmd/hashira-cui/editor.go, cmd/hashira-cui/keybinding.go, cmd/hashira-cui/main.go, cmd/hashira-cui/pane.go, cmd/hashira-cui/view.go
=> Fix gocui package, use jesseduffield's gocui

Gopkg.lock, Gopkg.toml, cmd/hashira-cui/editor.go, cmd/hashira-cui/keybinding.go, cmd/hashira-cui/main.go, cmd/hashira-cui/pane.go, cmd/hashira-cui/view.go, go.mod, go.sum
- change dependencies and import path to support install hashira-cui via go get
=> support "go get" to install latest hashira-cui

cmd/hashira-cui/editor.go
- fix Ctrl-a/e while editing to work correctly
=> [#86] fix Ctrl-a/e while editing

cmd/hashira-cui/editor.go
- Support Home/End key while editing.
- Same as Ctrl-a/e key while editing.  move cursor to start/end of line.
=> [#91] support Home/End key while editing

client/client.go, cmd/hashira-cui/main.go, cmd/hashira-cui/model.go, sync/syncutil/download.go, sync/syncutil/upload.go
- execute synchronization only when task or priority is dirty
- 10 minutes polling is removed
- make tasks clean after upload is finished
- don't run download if there's dirty task
=> Avoid overwrite if the task is dirty

.github/workflows/hashira-cui--test.yml
Fix golang layer CI 
It is the blocker for merging https://github.com/pankona/hashira/pull/833 and #836
=> Bump CI dependencies around golangci-lint

.github/dependabot.yml, .github/workflows/hashira-web--test.yml, hashira-web/.tool-versions, hashira-web/package.json, hashira-web/yarn.lock
Many dependabot PRs are failed from using old nodejs. See https://github.com/pankona/hashira/pull/827 as an example.
https://github.com/pankona/hashira/actions/runs/5258857960/jobs/9503647993#step:4:8
```
Run yarn install
yarn install v1.22.19
[1/[4](https://github.com/pankona/hashira/actions/runs/5258857960/jobs/9503647993#step:4:5)] Resolving packages...
[2/4] Fetching packages...
error firebase-tools@12.0.0: The engine "node" is incompatible with this module. Expected version ">=1[6](https://github.com/pankona/hashira/actions/runs/5258857960/jobs/9503647993#step:4:7).13.0 || >=1[8](https://github.com/pankona/hashira/actions/runs/5258857960/jobs/9503647993#step:4:9).0.0". Got "14.21.3"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation …
```
=> Fix WebApp CI with dependency issues

.github/workflows/hashira-cui--release.yml
Currently using old version for releasing than CI
=> release: Use the same version of go as specified in go.mod

cmd/hashira/commands.go, cmd/hashira/main.go, go.mod, go.sum
The latest is v2.3.2, however dependabot cant update because it can not access to gopkg.in
https://github.com/alecthomas/kingpin/blob/47025841275ac9c831e3d2707d77787367cbccab/README.md?plain=1#L129
=> Update alecthomas/kingpin hosting URL

hashira-web/package.json, hashira-web/yarn.lock
prettier is installed but not used anywhere. Some files look formatted, but some are not. CI does not exist around them.
I want to use formatters (especially dprint). But just having a dependency is not useful.
@pankona Do you have any plans to integrate with them?
=> Remove unused prettier dependency

hashira-web/src/TaskInput.tsx, hashira-web/src/hooks.ts, hashira-web/src/task.ts
Currently it looks like all inputs are submitted and saved.
I think rejecting duplicate tasks is a backend task. But just checking and preventing spaces will improve the frontend experience.
=> Prevent to add blank tasks in WebUI

hashira-web/src/AccessToken.tsx, hashira-web/src/TaskList.tsx
React provides `useId` hook, but we don't need it this time. We can handle on* events without ID property.
But I keep `data-taskId` in container.
Because it helps our debug in browser console
Fixes #873
=> Remove duplicated and needless id fields 

hashira-web/src/App.tsx, hashira-web/src/firebase.ts, hashira-web/src/hooks.ts
I think unnecessary to have 2 methods. Because the role is just duplicated.
=> Refactor duplicate and temporary named updateTask* methods

hashira-web/functions/Makefile, hashira-web/functions/func.go, hashira-web/src/firebase.ts, hashira-web/src/hooks.ts
Preparation part of #877 
There is a lot of deprecated code around cloud functions.
Looks like a squashed to an endpoint with a `method' param.
=> Remove deprecated functions

.github/workflows/dprint.yml, dprint.json
```console
> rtx exec dprint@0.39.1 -- dprint config update --yes
> rtx exec dprint@latest -- dprint check
> rtx ls dprint | tail -1
dprint 0.40.1
```
Fixes #935 
After merged this PR, #931, #932, #933, #934 should be rebased
- https://github.com/pankona/hashira/pull/871
=> Bump dprint config with old dprint binary

.github/dependabot.yml, .github/workflows/hashira-cui--test.yml, .github/workflows/hashira-web--test.yml, .github/workflows/hashira-web-functions--test.yml, hashira-web/package.json, hashira-web/yarn.lock
Resolves #1162
- とりあえず automerge はすべて止めた。今度は滞留すると思うのだけれど、壊れるの確実な状態で放置するよりましかと。解消できる方向性が見つかったら再開よろです (自分は https://github.com/pankona/pankona.github.com/pull/151 みたいにしているけれど、動くなら任意ので。定義がコードでリポジトリ内に管理されると嬉しい)
- 依存性はCI壊れながらも上がってしまった最新版で動くように頑張るほうが本筋というか将来性はありそうだけど、ライブラリ本家が対応してなかったり現状手をつけられる人が居ないので一旦動く範囲での最新版まですべて戻した
- その上で dependabot で対応バージョン上げてきそうなものをすべてオフにした。ここは本来上げるPRをもらいつつ赤くなったら直すみたいなのが正しいのだけれど、現状わかってるものをもらってもノイズになるだけなので
- マージ後に master で CI が殆ど走っていないから全部緑に見えるというのも気づくのに遅れた一因で、master はそのままデプロイに使うこともあるし push - master は基本CI対象にするほうが良いと思います。のでしておきました。
=> Fix many npm type errors with broken dependency updates

.github/workflows/merge-bot-pr.yml
Resolves #1167
マージ前に以下を有効にしてください
https://github.com/pankona/hashira/settings => Allow auto-merge
```bash
gh repo edit pankona/hashira --enable-auto-merge
```
https://github.com/pankona/hashira/settings/actions => Allow GitHub Actions to create and approve pull requests
```bash
gh api \
--method PUT \
-H "Accept: application/vnd.github+json" \
-H "X-GitHub-Api-Version: 2022-11-28" \
/repos/pankona/hashira/actions/permissions/workflow \
-f default_workflow_permissions='write' \
-F can_approve_pull_request_reviews=true
```
default_workflow_permissions は action 定義を dependabot が挙げてくるような時に影響しそうな気が・・・？ここは read のままでも動くかも
---
https://github.com/pankona/pankona.github.com/pull/151 同様のやり方でとりあえずPRを出しておきます！
とりあえず GITHUB_TOKEN を使ってるので、これによる マージ後の master では CI が走らなくなります。解消したければなんぞ APP を install して、そいつの …
=> Automatically merge dependabot PRs with GitHub Actions

hashira-web/functions/Makefile
- 非推奨（deprecated）な関数のデプロイコマンドを削除
- deploy-allターゲットを簡素化
- callのみを2nd gen対応で維持
=> refactor: remove deprecated functions from Makefile

hashira-web/src/App.tsx, hashira-web/src/TaskInput.tsx, hashira-web/src/hooks.ts
Add support for filtering tasks with multiple words separated by spaces and treating them as AND conditions.
* **hooks.ts**: Add a new hook `useFilteredTasks` to filter tasks based on multiple words.
* **App.tsx**: Import and use the new `useFilteredTasks` hook for filtering tasks. Add a filter input field and update the task display logic to show filtered tasks based on multiple words.
* **TaskInput.tsx**: Update the task input handling to support multiple word filters and pass them to the `useFilteredTasks` hook. Add a filter input field.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/pankona/hashira/pull/1305?shareId=61eced6e-ca76-4d82-8820-84a60904b8b3).
=> Update frontend to support multiple word filters

hashira-web/src/App.tsx, hashira-web/src/TaskList.tsx
タスク一覧の視認性を向上させるためのフィルター機能を追加: (1) Add Todos 入力欄の右側にフィルター用の入力欄を追加 (2) スペース区切りで複数のワードを指定可能（AND条件） (3) インクリメンタルなフィルタリング (4) フィルターの状態をブラウザのローカルストレージに保存 (5) ページ読み込み時に状態を復元
=> feat: add task filter with browser persistence

.github/workflows/hashira-cui--test.yml, .golangci.yml
https://github.com/pankona/hashira/pull/1287 以降 golangci-lint でCIが落ちている
```
jsonschema: "" does not validate with "/additionalProperties": additional properties 'skip-dirs' not allowed
Failed executing command with error: the configuration contains invalid elements
, Error: Command failed: /home/runner/golangci-lint-1.63.4-linux-amd64/golangci-lint config verify
jsonschema: "" does not validate with "/additionalProperties": additional properties 'skip-dirs' not allowed
Failed executing command with error: the configuration contains invalid elements
```
ログとか upstream の更新状況を見る限り https://github.com/golangci/golangci-lint-action/releases/tag/v6.5.0 で verify option がデフォルトで有効にされたため、もともと壊れていたが気付けなかった config schema の古さから落ちるようになったと思われる
https://github.com/golangci/golangci-lint-action/pull/1171 …
=> Fix failing golangci-lint in CI

.github/workflows/hashira-cui--test.yml, .golangci.yml, sync/client.go
https://github.com/pankona/hashira/pull/1330 で golangci-lint が cli-v1 系ですら落ちているのは直した
しかし世はすでに cli-v2 時代らしく、 https://github.com/pankona/hashira/pull/1327 みたいに action-v7 以降は cli-v1 をサポートしないらしい
ということで更新してみました。殆どツールが持ってる migration 機能と、その後に出してきたエラーを言われるがまま潰しただけです。
=> Bump golangci-lint to v2.x
