pankona/hashira

- cmd/hashira-cui/view.go
- cmd/hashira-cui/view_test.go
* move selected task's place on changing focus of pane
> [#21] move selected task's place on changing focus of pane

- .golangci.yml
- Gopkg.lock
- Gopkg.toml
- Makefile
- cmd/hashira-gui/bind.go
- database/boltdb.go
- database/boltdb_test.go
- hashira/client/client.go
- hashira/daemon/grpc.go
- hashira/daemon/grpc_test.go
* Updates
* add .golangci.yml as golangci configuration file
* introduce badge
> [#31] Introduce golangci as a part of CI

- cmd/hashira-cui/keybinding.go
- cmd/hashira-cui/view.go
- Press Escape key while input:
- exit inputting
- discard already inputted/modified texts
> [#67] Support ESC key to exit input

- Gopkg.lock
- cmd/hashira-cui/view.go
- go.mod
- fix cursor position at editing a line that contains wide charactor
> [#71] fix cursor position on editing

- cmd/hashira-cui/keybinding.go
- Support using arrow keys to navigate panes and tasks
> [#77] support arrow key to navigate focused pane and task

- client/client.go
- cmd/hashira-cui/editor.go
- cmd/hashira-cui/keybinding.go
- cmd/hashira-cui/model.go
- cmd/hashira-cui/view.go
- daemon/grpc.go
- daemon/grpc_test.go
- fix linter issues reported by golangci-lint
> [#88] refactor to fix linter issue

- README.md
- Update README.md. Remove limitations.
> [#93] update README.md to remove limitation

- .github/PULL_REQUEST_TEMPLATE.md
> [#90] add pull request template

- cmd/hashira-cui/view.go
- fix crash occured by index out of bounds in case glabbing focused task
> [#107] fix crash occured by index out of bounds

- cmd/hashira-cui/keybinding.go
- Support Delete key to delete a focused task
> [#109] support delete key to delete a focused task

- .circleci/config.yml
- cmd/hashira-cui/editor.go
- database/boltdb.go
- go.mod
- go.sum
> [#111] gometalinter free again

- cmd/hashira-auth/main.go
- declare structs that implements `http.Handler`
- separate sources by http end point
> Refactoring to separate souces by end point

- auth/accesstoken/accesstoken.go
- auth/google/google.go
- auth/me/me.go
- auth/twitter/twitter.go
- cmd/hashira-auth/main.go
- cmd/hashira-auth/router.go
- Refactoring directory structure for routing
> Refactoring directory structure for routing

- .circleci/config.yml
- .golangci.yml
- Makefile
- auth/google/google.go
- auth/me/me.go
- auth/twitter/twitter.go
- cmd/hashira-auth/main.go
- cmd/hashira-auth/router.go
- daemon/grpc.go
- store/datastore_test.go
- store/dsstore.go
- store/store.go
> Refactor datastore

- auth/google/google.go
- auth/me/me.go
- auth/twitter/twitter.go
- cmd/hashira-auth/main.go
- cmd/hashira-auth/router.go
- store/memstore.go
- user/user.go
- refactor stores to be able to inject from outside
> refactor stores to be able to inject from application

- cmd/hashira-auth/main.go
- read secrets.yaml for secret values
> refer secret.yaml to get secret values

- api/api.go
- cmd/hashira-api/main.go
- cmd/hashira-cui/ctrl.go
- cmd/hashirad/main.go
- daemon/grpc.go
- priorities.json
- tasks.json
> Download api

- Makefile
- cmd/hashira-api/main.go
- cmd/hashira-auth/main.go
- cmd/hashirad/main.go
- daemon/grpc.go
> Improve sync

- cmd/hashira-api/main.go
- cmd/hashira-auth/main.go
- cmd/hashira-frontend/src/components/App.jsx
- cmd/hashirad/main.go
- go.sum
- Specify server port by environment variables
> Specify port by env

- auth/google/google.go
- auth/me/me.go
- auth/twitter/twitter.go
- cmd/hashira-api/main.go
- cmd/hashira-auth/main.go
- cmd/hashira-frontend/README.md
- cmd/hashira-frontend/src/components/App.jsx
- Update brabra to run hashira on docker-compose
> update for running on docker-compose

- hashira-web/package.json
- hashira-web/yarn.lock
> resolve vulnerabilities

- hashira-web/functions/Makefile
- specify memory and max-instances for cloud functions
> specify memory and max-instances for cloud functions

- .gitignore
- Remove executable binary from version control
> Remove binary from version control

- cmd/hashira-web-client/download.go
- cmd/hashira-web-client/main.go
- hashira-web/functions/Makefile
- hashira-web/functions/func.go
- hashira-web/functions/go.mod
- hashira-web/functions/go.sum
- hashira-web/functions/hashira/hashira.go
- hashira-web/functions/hashira/hashira_test.go
- hashira-web/functions/hashira/store/tpstore.go
- implement download feature
- implement cloud functions for downloading
- implement download (and reflect to local task and priority) feature to hashira-web-client
> Implement download feature

- cmd/hashira-web-client/download.go
- cmd/hashira-web-client/main.go
- cmd/hashira-web-client/upload.go
- add `sync` command to hashira-web-client
> add sync command to hashira-web-client

- cmd/hashira-web-client/download.go
- merge old & new priorities in case of downloading
> append and unique new priorities and old priorities

- Makefile
- cmd/hashira-web-client/download.go
- cmd/hashira-web-client/main.go
- cmd/hashira-web-client/testaccesstoken.go
- cmd/hashira-web-client/upload.go
- go.mod
- syncclient/client.go
Refs: https://github.com/pankona/hashira/issues/269
- add syncclient package, that has responsibility to communicate with cloud functions to synchronize functionality
- refactor hashira-web-client to use the syncclient package
> add syncclient package

- cmd/hashira-web-client/main.go
- cmd/hashirad/main.go
- syncutil/client.go
- syncutil/download.go
- syncutil/testaccesstoken.go
- syncutil/upload.go
Refs: #269 
- sync with firestore in 10 minutes interval if HASHIRA_ACCESSTOKEN is set in environment variables
> sync in 10 minutes interval

- cmd/hashirad/main.go
- hashira-web/functions/hashira/upload.go
- hashira-web/functions/hashira/upload_test.go
- syncutil/upload.go
Refs: #269 
- sanitize duplicated priorities
> Sanitize priorities if duplicated

- cmd/hashira-cui/main.go
- do test access token in async
> do test access token in async to increase launch speed

- hashira-web/src/App.tsx
- hashira-web/src/firebase.ts
- remove unused imports and console.log
> [hashira-web] remove unused imports and console.log

- hashira-web/src/App.tsx
- improve performance by parallel request
> small performance improvement

- hashira-web/yarn.lock
> yarn upgrade

- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-pull-request.yml
- hashira-web/build.go
- hashira-web/src/App.tsx
- hashira-web/src/revision.ts
- show build version of hashira-web
> show build version

- hashira-web/src/App.tsx
- show "loading..." while loading tasks and priorities
> add loading indicator

- hashira-web/src/App.tsx
- show input field without login confirmation
> show input field without login confirmation

- hashira-web/functions/hashira/merge.go
- hashira-web/functions/hashira/merge_test.go
- hashira-web/functions/hashira/upload.go
- change priority merging strategy
- merge priorities in alternately
> change priority merging strategy

- hashira-web/functions/Makefile
- hashira-web/functions/func.go
- hashira-web/functions/hashira/add.go
- hashira-web/src/App.tsx
- hashira-web/src/firebase.ts
- support bulk uploading from hashira-web
> Add add function to support bulk upload

- hashira-web/src/firebase.ts
- add missing type declaration for tasksObject
> declare type for tasksObject

- hashira-web/src/App.tsx
- hashira-web/src/TaskList.tsx
- hashira-web/src/firebase.ts
- add checkbox to support to mark tasks as done/remove
> add checkbox to mark tasks as done or remove

- hashira-web/src/App.tsx
> hide mark as done button if user is not logged in

- hashira-web/src/TaskList.tsx
- don't scroll checkbox if the content is scrollable not to disappear the checkbox
> don't scroll checkbox

- hashira-web/src/App.tsx
- hashira-web/src/TaskList.tsx
- hashira-web/src/firebase.ts
- edit tasks by editing and focus out from tasks
> edit tasks by edit and out focus from tasks

- hashira-web/src/App.tsx
- hashira-web/src/TaskInput.tsx
> fix submit bug

- cmd/hashira-cui/main.go
- cmd/hashira-cui/model.go
- sync/client.go
> sync on launch immediately

- hashira-web/src/TaskList.tsx
- fix crash if there's some lane which is empty
> consider the case tasksAndPriorities["Priority"][place] is empty

- hashira-web/src/App.tsx
- hashira-web/src/TaskList.tsx
- add move button to move tasks to its neighbor pane
> add move button

- hashira-web/src/App.tsx
- hashira-web/src/TaskList.tsx
> implement onMoveTask

- hashira-web/src/App.tsx
- hashira-web/src/Header.tsx
- hashira-web/src/TaskInput.tsx
> tweak space and button sizes

- hashira-web/src/App.tsx
- hashira-web/src/TaskInput.tsx
- hashira-web/src/styles.ts
- move common styles to styles.ts
> move common styles to styles.ts

- hashira-web/src/App.tsx
- hashira-web/src/TaskInput.tsx
- hashira-web/src/TaskList.tsx
- hashira-web/src/hooks.ts
> refactor to use custom hooks entirely

- hashira-web/src/TaskList.tsx
- hashira-web/src/firebase.ts
- refactor long functions that are declared on `onChange` directory to put components
> refactor long function and add some comments

- hashira-web/src/App.tsx
- hashira-web/src/Header.tsx
- don't show loading if user is not logged in
> don't show loading indicator if user is not definitely logged in

- cmd/hashira-cui/main.go
- fix crash if hashira-cui runs on WSL
> don't use syslog if failed to retrieve syslog

- go.mod
> update go.mod to use go 1.17

- hashira-web/functions/Makefile
- hashira-web/functions/func.go
> add ping functions

- hashira-web/functions/Makefile
- hashira-web/functions/func.go
- all functions will be called via call function
- for cold start problem
> add call function

- hashira-web/src/App.tsx
- hashira-web/src/firebase.ts
- use `call` function to use cloud fucntions
> Use call method to call cloud functions

- .github/dependabot.yml
- add `automerge` label to pull requests from dependabot
> add automerge label to PRs from dependabot

- hashira-web/src/TaskList.tsx
- add title to each lane
- add "no item" label if there's no items in a lane
> add title to each lane

- hashira-web/src/firebase.ts
- hashira-web/src/hooks.ts
- store user data on local storage to increase performance
> Store user on localStorage

- hashira-web/.gitignore
- hashira-web/package.json
- hashira-web/src/AccessToken.tsx
- hashira-web/src/App.tsx
- hashira-web/src/Header.tsx
- hashira-web/src/Router.tsx
- hashira-web/src/index.tsx
- hashira-web/yarn.lock
- separate access tokens feature from main page
> Separate access token page from main page

- hashira-web/src/AccessToken.tsx
- hashira-web/src/App.tsx
- hashira-web/src/Header.tsx
- don't wait loading completion to show header
> Fix glitch in header

- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-pull-request.yml
Same as https://github.com/pankona/hashira/pull/838, #840
> deploying: Use the same version of go as specified in go.mod

- .github/workflows/hashira-web--test.yml
> Fix wrong use of action and the toolset

- .github/workflows/hashira-cui--test.yml
> Skip CUI CI if changed non related workflows

- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-pull-request.yml
Because contributor and dependebot does not have the rights to read secret
https://github.com/pankona/hashira/pull/841#issuecomment-1598664103
> Skip deploying when the actor is not author

- hashira-web/package.json
- hashira-web/yarn.lock
> Remove unused type definition for ws

- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-pull-request.yml
- .github/workflows/hashira-web--test.yml
> Adjust use of yarn with setup-node recommended way

- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-pull-request.yml
I don't know the detail of clound functions deploying. But atleast this code is wrong for handling frontend environments.
> Fix wrong use of setup-node and setup-go as #842

- hashira-web/src/firebase.ts
Resolves #864
option1 described in https://firebase.google.com/docs/auth/web/redirect-best-practices?hl=ja
> Update firebase authentication

- .github/dependabot.yml
- .github/workflows/dprint.yml
- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-pull-request.yml
- .github/workflows/hashira-cui--release.yml
- .github/workflows/hashira-cui--test.yml
- .github/workflows/hashira-web--test.yml
- .github/workflows/hashira-web-functions--test.yml
- Makefile
- README.md
- dprint.json
- hashira-web/src/AccessToken.tsx
- hashira-web/src/App.tsx
- hashira-web/src/Header.tsx
- hashira-web/src/Router.tsx
- hashira-web/src/TaskInput.tsx
- hashira-web/src/TaskList.tsx
- hashira-web/src/firebase.ts
- hashira-web/src/hooks.ts
- hashira-web/vite.config.ts
ref: https://github.com/pankona/hashira/pull/866, https://github.com/pankona/hashira/issues/869
This configuration is not my preference. It keeps zero configration as possible we can.
Because I respect the pankona wish as he said as https://github.com/mobu-of-the-world/mobu/pull/489#issuecomment-1172006167.
> Integrate dprint

- hashira-web/src/App.tsx
> Prevent duplicate API calls when the multiple movements are triggered in a short

- .github/dependabot.yml
#1162 の一環で、高頻度で上がってきても現状特に目を通せていないという状況だと思うので延ばしておきました！(追いきれない中で立て続けにマージされていくと悪化するので)
> Relax dependabot schedule

- .github/workflows/dprint.yml
- dprint.json
> Replace prettier plugin with pretty_yaml for YAML formatter

- .github/workflows/hashira-cui--test.yml
- cmd/hashira-cui/view.go
- database/boltdb_test.go
- go.mod
- go.sum
Updated Go version to the latest stable release
> Update Go version to 1.23.5

- hashira-web/.tool-versions
This PR updates the Node version and confirms that the build is successful.
> Update Node Version

- hashira-web/src/App.tsx
- hashira-web/src/TaskInput.tsx
- hashira-web/src/hooks.ts
> Revert "Update frontend to support multiple word filters"

- hashira-web/src/Header.tsx
- hashira-web/src/Router.tsx
- hashira-web/src/Tags.tsx
タグ管理機能を追加しました：
- タグ一覧を表示・編集できる Tags コンポーネントを追加
- タグ名をクリックすると、そのタグでフィルタリングされたタスク一覧に遷移
- タグの編集機能（タグ名の変更）を実装
- タグ一覧とタスク一覧間のナビゲーションを実装
1. タグ一覧画面を開く
2. タグをクリックしてタスク一覧に遷移することを確認
3. タグの編集機能が正常に動作することを確認
> feat: add tag management feature

- hashira-web/package.json
- hashira-web/yarn.lock
https://github.com/pankona/hashira/pull/1290/files#r2024156464
> Bump "@types/node" to follow #1290
